=== ahdis/ch-alis/input/resources/binary/LeistungsschnittstelleV50.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Leistungsschnittstelle ALIS Version 5.0 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="5.0">
	<xs:element name="Header">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReceivingApplication">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ReceivingFacility">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="10" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ReceivingServiceCode">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SendingApplication">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SendingFacility">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="10" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SendingServiceCode">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MessageControlID" type="xs:unsignedInt" />
				<xs:element name="HeaderErrorCode" type="xs:string" minOccurs="0" />
				<xs:element name="SoftwareReleaseNumber">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FileCreationDate" type="xs:dateTime" minOccurs="0" />
				<xs:element name="Visit" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="VisitNumber" type="xs:string" />
							<xs:element name="PatientID" type="xs:normalizedString" minOccurs="0" />
							<xs:element name="PatientName" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PatientGivenName" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PatientBirthDate" type="xs:date" minOccurs="0" />
							<xs:element name="PatientGender" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="M|F" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TerminationVisit" type="xs:date" minOccurs="0" />
							<xs:element name="TerminationReason" type="xs:string" minOccurs="0" />
							<xs:element name="DiagGroup" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DiagType" type="xs:string" minOccurs="0" />
										<xs:element name="DiagCatType" type="xs:string" minOccurs="0" />
									</xs:sequence>
									<xs:attribute name="DiagCode" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="Service" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation />
									<xs:documentation>Leistungen stehen zum Patient im VerhÃ¤ltnis 1:N</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ServiceDate" type="xs:dateTime" />
										<xs:element name="SessionID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="64" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OrderID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="64" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OrderDate" type="xs:dateTime" minOccurs="0" />
										<xs:element name="ReferrerID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ServiceType" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<!-- 5.00 increased to 20-->
													<xs:maxLength value="20" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ServiceItem" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1" />
													<xs:maxLength value="20" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Form" type="xs:string" minOccurs="0" />
										<xs:element name="EnteredDateTime" type="xs:dateTime" minOccurs="0" />
										<xs:element name="ProviderID" type="xs:string" minOccurs="0" />
										<xs:element name="EnteredBy" type="xs:string" minOccurs="0" />
										<xs:element name="PatientContactID" type="xs:string" minOccurs="0" />
										<xs:element name="ItemNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="64" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="RefItemNumber" type="xs:string" minOccurs="0" />
										<xs:element name="Quantity" type="xs:float" minOccurs="0" />
										<xs:element name="Costweight" type="xs:float" minOccurs="0" />
										<xs:element name="ServiceItemErrorCode" type="xs:string" minOccurs="0" />
										<xs:element name="PersonV40" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="PersonID" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="PersonTyp" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string" />
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
											<xs:unique name="ConstPersonTyp">
												<xs:selector xpath="Header/Visit/Service/PersonV40" />
												<xs:field xpath="@PersonTyp" />
											</xs:unique>
										</xs:element>
										<xs:element name="ParameterV40" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ParamValue" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="ParamTyp" type="xs:string" use="required" />
											</xs:complexType>
											<xs:unique name="ConstParamTyp">
												<xs:selector xpath="Header/Visit/Service/ParameterV40" />
												<xs:field xpath="@ParamTyp" />
											</xs:unique>
										</xs:element>
										<xs:element name="Diagnosis" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Identifier" type="xs:string"  minOccurs="0" />
													<xs:element name="Category" type="xs:string" minOccurs="1" />
													<xs:element name="Code" type="xs:string" minOccurs="1" />
													<xs:element name="Display" type="xs:string" minOccurs="0" />
													<xs:element name="OnsetDateTime" type="xs:dateTime" minOccurs="0" />
													<xs:element name="Laterality" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="l|r|b" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Procedure" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Identifier" type="xs:string" minOccurs="0" />
													<xs:element name="Category" type="xs:string" minOccurs="1" />
													<xs:element name="Code" type="xs:string" minOccurs="1" />
													<xs:element name="Display" type="xs:string" minOccurs="0" />
													<xs:element name="PerformedDateTime" type="xs:dateTime" minOccurs="0" />
													<xs:element name="Laterality" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="l|r|b" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Performer" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Function" type="xs:string" minOccurs="1" />
																<xs:element name="Identifier" type="xs:string" minOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Transaction" type="xs:string" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Version" type="xs:float" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ahdis/ch-alis/input/resources/binary/amb_Pauschalen_2024_04_05_CHOP_ICD.xml
<?xml version="1.0" encoding="UTF-8"?>
<Header xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5.0" xsi:noNamespaceSchemaLocation="LeistungsschnittstelleV50.xsd">
	<ReceivingApplication>TARDOC Test</ReceivingApplication>
	<ReceivingFacility>1234</ReceivingFacility>
	<ReceivingServiceCode>Radiologie</ReceivingServiceCode>
	<SendingApplication>ALIS</SendingApplication>
	<SendingFacility>4321</SendingFacility>
	<SendingServiceCode>4321</SendingServiceCode>
	<MessageControlID>1262557</MessageControlID>
	<SoftwareReleaseNumber>1.1.0</SoftwareReleaseNumber>
	<FileCreationDate>2024-04-05T10:06:44Z</FileCreationDate>
	<Visit>
		<VisitNumber>987654</VisitNumber>
		<PatientID>102</PatientID>
		<PatientName>Tester</PatientName>
		<PatientGivenName>Paul</PatientGivenName>
		<PatientBirthDate>1982-03-22</PatientBirthDate>
		<PatientGender>M</PatientGender>
		<Service Transaction="insert">
			<ServiceDate>2024-04-04T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20240405-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<PatientContactID>20230404-1</PatientContactID>
			<Diagnosis>
				<Identifier>DIAG1</Identifier>
				<Category>ICD10_2023</Category>
				<Code>B01.2</Code>
				<Display>Varizellen-Pneumonie</Display>
				<Laterality>l</Laterality>
			</Diagnosis>
			<Procedure>
				<Identifier>PROC1</Identifier>
				<Category>CHOP_2023</Category>
				<Code>87.41.99</Code>
				<Display>Computertomographie des Thorax, sonstige</Display>
				<OccurrenceDateTime>2024-04-04T10:06:50Z</OccurrenceDateTime>
				<Laterality>l</Laterality>			
				<Performer>
					<Function>ResponsiblePhysician</Function>
					<Identifier>7653253256999</Identifier>
				</Performer>
			</Procedure>
		</Service>
	</Visit>
</Header>

=== ahdis/ch-alis/input/resources/binary/Alis5TARDOC.xml
<?xml version="1.0" encoding="UTF-8"?>
<Header xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5.0" xsi:noNamespaceSchemaLocation="LeistungsschnittstelleV50.xsd">
	<ReceivingApplication>TARDOCTest</ReceivingApplication>
	<ReceivingFacility>1234</ReceivingFacility>
	<ReceivingServiceCode>Radiologie</ReceivingServiceCode>
	<SendingApplication>ALIS</SendingApplication>
	<SendingFacility>4321</SendingFacility>
	<SendingServiceCode>4321</SendingServiceCode>
	<MessageControlID>1262556</MessageControlID>
	<SoftwareReleaseNumber>1.1.0</SoftwareReleaseNumber>
	<FileCreationDate>2024-04-05T10:06:44Z</FileCreationDate>
	<Visit>
		<VisitNumber>987654</VisitNumber>
		<PatientID>102</PatientID>
		<PatientName>Tester</PatientName>
		<PatientGivenName>Paul</PatientGivenName>
		<PatientBirthDate>1982-03-22</PatientBirthDate>
		<PatientGender>M</PatientGender>
		<Service Transaction="insert">
			<ServiceDate>2024-04-05T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20240405-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>TARDOC_1.3.2</ServiceType>
			<ServiceItem>MA.00.0040</ServiceItem>
			<EnteredDateTime>2024-04-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45678</ItemNumber>
			<Quantity>1</Quantity>
			<PersonV40 PersonTyp="ResponsiblePhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
			<PersonV40 PersonTyp="ProvidingPhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
		</Service>
		<Service Transaction="insert">
			<ServiceDate>2024-04-05T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20240405-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>TARDOC_1.3.2</ServiceType>
			<ServiceItem>MA.00.0050</ServiceItem>
			<EnteredDateTime>2024-04-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45679</ItemNumber>
			<RefItemNumber>45678</RefItemNumber>
			<Quantity>1</Quantity>
			<PersonV40 PersonTyp="ResponsiblePhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
			<PersonV40 PersonTyp="ProvidingPhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
		</Service>
	</Visit>
</Header>

=== ahdis/ch-alis/input/resources/binary/Analysenliste_2024_04_05.xml
<?xml version="1.0" encoding="UTF-8"?>
<Header xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5.0" xsi:noNamespaceSchemaLocation="LeistungsschnittstelleV50.xsd">
	<ReceivingApplication>TARDOC Test</ReceivingApplication>
	<ReceivingFacility>1234</ReceivingFacility>
	<ReceivingServiceCode>Radiologie</ReceivingServiceCode>
	<SendingApplication>ALIS</SendingApplication>
	<SendingFacility>4321</SendingFacility>
	<SendingServiceCode>4321</SendingServiceCode>
	<MessageControlID>1262556</MessageControlID>
	<SoftwareReleaseNumber>1.1.0</SoftwareReleaseNumber>
	<FileCreationDate>2024-04-05T10:06:44Z</FileCreationDate>
	<Visit>
		<VisitNumber>987654</VisitNumber>
		<PatientID>102</PatientID>
		<PatientName>Tester</PatientName>
		<PatientGivenName>Paul</PatientGivenName>
		<PatientBirthDate>1982-03-22</PatientBirthDate>
		<PatientGender>M</PatientGender>
		<Service Transaction="insert">
			<ServiceDate>2024-04-05T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20240405-1</OrderID>
			<OrderDate>2024-04-04T10:00:00Z</OrderDate>
			<ReferrerID>007</ReferrerID>
			<ServiceType>AL2024</ServiceType>
			<ServiceItem>1021.00</ServiceItem>
			<EnteredDateTime>2024-04-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2300</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45678</ItemNumber>
			<Quantity>1</Quantity>
		</Service>
	</Visit>
</Header>
