=== ahdis/ch-alis/input/resources/binary/LeistungsschnittstelleV51.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Leistungsschnittstelle ALIS Version 5.1 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="5.1">
	<xs:element name="Header">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ReceivingApplication">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ReceivingFacility">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="10" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ReceivingServiceCode">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SendingApplication">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SendingFacility">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="10" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="SendingServiceCode">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MessageControlID" type="xs:unsignedInt" />
				<xs:element name="HeaderErrorCode" type="xs:string" minOccurs="0" />
				<xs:element name="SoftwareReleaseNumber">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FileCreationDate" type="xs:dateTime" minOccurs="0" />
				<xs:element name="Visit" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="VisitNumber" type="xs:string" />
							<xs:element name="PatientID" type="xs:normalizedString" minOccurs="0" />
							<xs:element name="PatientName" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PatientGivenName" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PatientBirthDate" type="xs:date" minOccurs="0" />
							<xs:element name="PatientGender" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="M|F" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TerminationVisit" type="xs:date" minOccurs="0" />
							<xs:element name="TerminationReason" type="xs:string" minOccurs="0" />
							<!-- 5.1 removed DiagGroup-
							<xs:element name="DiagGroup" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="DiagType" type="xs:string" minOccurs="0" />
										<xs:element name="DiagCatType" type="xs:string" minOccurs="0" />
									</xs:sequence>
									<xs:attribute name="DiagCode" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							-->
							<xs:element name="Service" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation />
									<xs:documentation>Leistungen stehen zum Patient im Verh√§ltnis 1:N</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ServiceDate" type="xs:dateTime" />
										<xs:element name="SessionID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="64" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="OrderID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="64" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!-- new in 5.1-->
										<xs:element name="OrderDate" type="xs:dateTime" minOccurs="0" />
										<xs:element name="ReferrerID" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ServiceType" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<!-- 5.1 increased to 20-->
													<xs:maxLength value="20" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<!-- optional Tarifposition in 5.1?-->
										<xs:element name="ServiceItem" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1" />
													<xs:maxLength value="20" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Form" type="xs:string" minOccurs="0" />
										<xs:element name="EnteredDateTime" type="xs:dateTime" minOccurs="0" />
										<xs:element name="ProviderID" type="xs:string" minOccurs="0" />
										<xs:element name="EnteredBy" type="xs:string" minOccurs="0" />
										<xs:element name="ItemNumber" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="64" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="RefItemNumber" type="xs:string" minOccurs="0" />
										<!-- 5.1 xs:float? optional in schema but not win word-->
										<xs:element name="Quantity" type="xs:float" minOccurs="0" />
										<!-- new in 5.1, xs:decimal ? -->
										<xs:element name="TPValue" type="xs:float" minOccurs="0" />
										<xs:element name="ServiceItemErrorCode" type="xs:string" minOccurs="0" />
										<!-- new in 5.1 -->
										<xs:element name="SessionSectionB" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SessionIDSectionB"> 
														<xs:simpleType>
															<xs:annotation>
																<xs:documentation xml:lang="en">GUID</xs:documentation>
															</xs:annotation>
															<xs:restriction base="xs:string">
																<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="AssignedSessionSectionB" minOccurs="0">
														<xs:simpleType>
															<xs:annotation>
																<xs:documentation xml:lang="en">GUID</xs:documentation>
															</xs:annotation>
															<xs:restriction base="xs:string">
																<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="TrueSessionSectionB" type="xs:boolean" minOccurs="0" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<!-- new in 5.1-->
										<xs:element name="Diagnosis" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="DiagnosisCode" type="xs:string" minOccurs="1" />
													<xs:element name="DiagnosisSystem" type="xs:string" minOccurs="1" />
													<xs:element name="DiagnosisVersion" type="xs:string" minOccurs="1" />
													<xs:element name="DiagnosisConfidential" type="xs:boolean" minOccurs="0" />
													<xs:element name="OnSetDateTime" type="xs:dateTime" minOccurs="0" />
													<xs:element name="Laterality" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="l|r|b" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="ServiceAssignment" minOccurs="0" >
											<xs:complexType>
												<xs:sequence>
													<xs:element name="OrderingProviderID" type="xs:string" minOccurs="0" />
													<xs:element name="OrderReportDate" type="xs:dateTime" minOccurs="0" />
													<xs:element name="FollowUpOrder" type="xs:boolean" minOccurs="0" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="PersonV40" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="PersonID" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="PersonTyp" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string" />
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
											<xs:unique name="ConstPersonTyp">
												<xs:selector xpath="Header/Visit/Service/PersonV40" />
												<xs:field xpath="@PersonTyp" />
											</xs:unique>
										</xs:element>
										<xs:element name="ParameterV40" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ParamValue" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="ParamTyp" type="xs:string" use="required" />
											</xs:complexType>
											<xs:unique name="ConstParamTyp">
												<xs:selector xpath="Header/Visit/Service/ParameterV40" />
												<xs:field xpath="@ParamTyp" />
											</xs:unique>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Transaction" type="xs:string" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Version" type="xs:float" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ahdis/ch-alis/input/resources/binary/Alis51LKAATIcd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Header xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5.1" xsi:noNamespaceSchemaLocation="LeistungsschnittstelleV51.xsd">
	<ReceivingApplication>TARDOC Test</ReceivingApplication>
	<ReceivingFacility>1234</ReceivingFacility>
	<ReceivingServiceCode>Radiologie</ReceivingServiceCode>
	<SendingApplication>ALIS</SendingApplication>
	<SendingFacility>4321</SendingFacility>
	<SendingServiceCode>4321</SendingServiceCode>
	<MessageControlID>1262557</MessageControlID>
	<SoftwareReleaseNumber>1.1.0</SoftwareReleaseNumber>
	<FileCreationDate>2024-04-05T10:06:44Z</FileCreationDate>
	<Visit>
		<VisitNumber>987654</VisitNumber>
		<PatientID>102</PatientID>
		<PatientName>Tester</PatientName>
		<PatientGivenName>Paul</PatientGivenName>
		<PatientBirthDate>1982-03-22</PatientBirthDate>
		<PatientGender>M</PatientGender>
		<Service Transaction="insert">
			<ServiceDate>2025-03-05T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20250305-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>LKAAT</ServiceType>
			<ServiceItem>GM.00.0140</ServiceItem>
			<EnteredDateTime>2025-03-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45678</ItemNumber>
			<Quantity>1</Quantity>
			<Diagnosis>
				<DiagnosisCode>B01.2</DiagnosisCode>
				<DiagnosisSystem>ICD</DiagnosisSystem>
				<DiagnosisVersion>2023</DiagnosisVersion>
			</Diagnosis>
			<PersonV40 PersonTyp="ResponsiblePhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
			<PersonV40 PersonTyp="ProvidingPhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
		</Service>
		<Service>
			<ServiceDate>2024-04-05T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20250305-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>LKAAT</ServiceType>
			<ServiceItem>GM.10.0010</ServiceItem>
			<EnteredDateTime>2025-03-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45679</ItemNumber>
			<RefItemNumber>45678</RefItemNumber>
			<Quantity>1</Quantity>
			<PersonV40 PersonTyp="ResponsiblePhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
			<PersonV40 PersonTyp="ProvidingPhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
		</Service>
		<Service>
			<ServiceDate>2024-04-05T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>20250305-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>LKAAT</ServiceType>
			<ServiceItem>GM.15.0020</ServiceItem>
			<EnteredDateTime>2025-03-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45680</ItemNumber>
			<RefItemNumber>45678</RefItemNumber>
			<Quantity>20</Quantity>
			<PersonV40 PersonTyp="ResponsiblePhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
			<PersonV40 PersonTyp="ProvidingPhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>
		</Service>
	</Visit>
</Header>

=== ahdis/ch-alis/input/resources/binary/Alis51PauschaleKomplett.xml
<?xml version="1.0" encoding="UTF-8"?>
<Header xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5.1" xsi:noNamespaceSchemaLocation="LeistungsschnittstelleV51.xsd">
	<ReceivingApplication>TARDOC Test</ReceivingApplication>
	<ReceivingFacility>1234</ReceivingFacility>
	<ReceivingServiceCode>Radiologie</ReceivingServiceCode>
	<SendingApplication>ALIS</SendingApplication>
	<SendingFacility>4321</SendingFacility>
	<SendingServiceCode>4321</SendingServiceCode>
	<MessageControlID>1262557</MessageControlID>
	<SoftwareReleaseNumber>1.1.0</SoftwareReleaseNumber>
	<FileCreationDate>2024-04-05T10:06:44Z</FileCreationDate>
	<Visit>
		<VisitNumber>987654</VisitNumber>
		<PatientID>102</PatientID>
		<PatientName>Tester</PatientName>
		<PatientGivenName>Paul</PatientGivenName>
		<PatientBirthDate>1982-03-22</PatientBirthDate>
		<PatientGender>M</PatientGender>
		<Service Transaction="insert">
			<ServiceDate>2025-03-04T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>2025403-1</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>Pauschalen_1.0</ServiceType>
			<ServiceItem>C30.30E</ServiceItem>
			<EnteredDateTime>2025-05-05T10:05:36Z</EnteredDateTime>
			<ProviderID>2400</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>45678</ItemNumber>
			<Quantity>1</Quantity>
			<TPValue>0.85</TPValue>
			<Diagnosis>
				<DiagnosisCode>B01.2</DiagnosisCode>
				<DiagnosisSystem>ICD10</DiagnosisSystem>
				<DiagnosisVersion>2023</DiagnosisVersion>
				<DiagnosisConfidential>0</DiagnosisConfidential>
			</Diagnosis>				
			<PersonV40 PersonTyp="ResponsiblePhysician">
				<PersonID>7653253256988</PersonID>
			</PersonV40>			
		</Service>
	</Visit>
</Header>

=== ahdis/ch-alis/input/resources/binary/Alis51LabServiceAssignment.xml
<?xml version="1.0" encoding="UTF-8"?>
<Header xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="5.1" xsi:noNamespaceSchemaLocation="LeistungsschnittstelleV51.xsd">
	<ReceivingApplication>TARDOC Test</ReceivingApplication>
	<ReceivingFacility>1234</ReceivingFacility>
	<ReceivingServiceCode>Labor</ReceivingServiceCode>
	<SendingApplication>ALIS</SendingApplication>
	<SendingFacility>4321</SendingFacility>
	<SendingServiceCode>4321</SendingServiceCode>
	<MessageControlID>1262557</MessageControlID>
	<SoftwareReleaseNumber>1.1.0</SoftwareReleaseNumber>
	<FileCreationDate>2025-04-07T10:06:44Z</FileCreationDate>
	<Visit>
		<VisitNumber>987654</VisitNumber>
		<PatientID>102</PatientID>
		<PatientName>Tester</PatientName>
		<PatientGivenName>Paul</PatientGivenName>
		<PatientBirthDate>1982-03-22</PatientBirthDate>
		<PatientGender>M</PatientGender>
		<Service Transaction="insert">
			<ServiceDate>2025-03-04T09:00:00Z</ServiceDate>
			<SessionID>1</SessionID>
			<OrderID>2025403-2</OrderID>
			<ReferrerID>007</ReferrerID>
			<ServiceType>AL2025</ServiceType>
			<ServiceItem>1368.00</ServiceItem>
			<EnteredDateTime>2025-05-05T10:05:36Z</EnteredDateTime>			
			<ProviderID>2700</ProviderID>
			<EnteredBy>7653253256988</EnteredBy>
			<ItemNumber>46784</ItemNumber>
			<Quantity>1</Quantity>
			<ServiceAssignment>
				<OrderingProviderID>7653253258966</OrderingProviderID>
				<OrderReportDate>2025-03-04T10:05:36Z</OrderReportDate>
				<FollowUpOrder>0</FollowUpOrder>
			</ServiceAssignment>
		</Service>
	</Visit>
</Header>
